### ISSUE TITLE
Feature Request - Command Line Utility

### ISSUE THREAD

**Issue by baldsealion** [project-sbc/Power-Control-Panel-v2#19]
Would like the ability to set Sustained TDP and Boost TDP with command line switches. Is this possible?

**Comment by project-sbc** [comment]
You mean set them both at the same time?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: baldsealion ***@***.***>
Sent: Wednesday, September 21, 2022 12:46:29 PM
To: project-sbc/Power-Control-Panel-v2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [project-sbc/Power-Control-Panel-v2] Feature Request - Command Line Utility (Issue #19)


Would like the ability to set Sustained TDP and Boost TDP with command line switches. Is this possible?

**Comment by baldsealion** [comment]
Nevermind, I realized today this utilizes ryzenadj and I can just use that directly with command line switches.

please disregard.
