### ISSUE TITLE
Settings titles overlaps current selection

### ISSUE THREAD

**Issue by ion2903** [project-sbc/Power-Control-Panel-v2#22]
Some settings titles in quick-access menu is overlapping combo-boxes of those settings.
![20220922_152834](https://user-images.githubusercontent.com/13135577/191748858-ecf2c410-4010-4cb2-8297-db2091ed522c.jpg)

**Comment by project-sbc** [comment]
There is a setting that changes QAM width, you can also drag it. Let me know if that fixes it for you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: ion2903 ***@***.***>
Sent: Thursday, September 22, 2022 8:38:13 AM
To: project-sbc/Power-Control-Panel-v2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [project-sbc/Power-Control-Panel-v2] Settings titles overlaps current selection (Issue #22)


Some settings titles in quick-access menu is overlapping combo-boxes of those settings.
[20220922_152834]<https://user-images.githubusercontent.com/13135577/191748858-ecf2c410-4010-4cb2-8297-db2091ed522c.jpg>

**Comment by ion2903** [comment]
Available QAM width from settings is not enough, but dragging it manually all the way to ~60% makes it look ok. 
Also when it's 60% width, tiles is sorted by 4 in row, which removes my other issue about QAM not scrolling down automatically to newly opened submenu.

**Comment by project-sbc** [comment]
Should be fixed as of 0.2.0

**Comment by ion2903** [comment]
![image](https://user-images.githubusercontent.com/13135577/196630790-3f16d1e2-04c2-4faf-a743-9d1fbb418dfd.png)
No, it's not :)
