### ISSUE TITLE
Quick-access menu submenu closing

### ISSUE THREAD

**Issue by ion2903** [project-sbc/Power-Control-Panel-v2#23]
In tile-grouped quick-access menu submenu of selected system control is closing as soon as I release my finger from slider (same with mouse click).

**Comment by ion2903** [comment]
https://disk.yandex.ru/i/DluMqP-D45XLGQ - link to video, since GitHub won't allow me to upload it here directly.

**Comment by project-sbc** [comment]
Fixed as of 0.2.0
