### ISSUE TITLE
Encountering a strange issue when mirroring display on the Aya Neo Air Pro.

### ISSUE THREAD

**Issue by dot-bob** [project-sbc/Power-Control-Panel-v2#25]
I have the Aya Neo Air Pro with the Ryzen 7 5825U.  The display on the Air needs the display rotation setting in windows 11 to be set in landscape flipped to be in the correct orientation.  An attached external display is normally just set to normal landscape orientation.  I had been using the device off and on while duplicating the displays for a while without issue.

I decided to try the setting in Power Control Panel V2 to change the screen resolution and when I did the external display changed to landscape flipped orientation.  I changed back to previous resolution but there was no change to orientation on external monitor.  Since the orientation option in windows is greyed out when duplicating displays I changed to extend desktop fixed the orientation on the second display but when switching back to duplicating displays the external display flips back to being upside down.  The problem only happens when duplicating and not when extending or using the external display only.  It even seems to be doing it when casting and mirroring using the microsoft wireless display adapter as well.

Unfortunately there is no setting in the amd control center to fix it only a redirection to the windows settings that are greyed out when duplicating displays.

**Comment by project-sbc** [comment]
yeah multi display resolution changing gets tricky with my method. I don't have a viable solution or work around for this.
