### ISSUE TITLE
No auto-start

### ISSUE THREAD

**Issue by ion2903** [project-sbc/Power-Control-Panel-v2#29]
0.1.13 for some reason not starting on system startup even when "Start With Windows" is set to Enable.

**Comment by project-sbc** [comment]
Are you on discord? I would like to try and diagnose further if you are willing to help

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: ion2903 ***@***.***>
Sent: Friday, October 7, 2022 1:44:47 AM
To: project-sbc/Power-Control-Panel-v2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [project-sbc/Power-Control-Panel-v2] No auto-start (Issue #29)


0.1.13 for some reason not starting on system startup even when "Start With Windows" is set to Enable.

**Comment by ion2903** [comment]
> 

Yes, it's ion2903#2606

**Comment by project-sbc** [comment]
issue will be fixed in next release 0.1.14. After updating, the task scheduler needs its link updated
