### ISSUE TITLE
Hotkeys don't work.

### ISSUE THREAD

**Issue by sanpats** [project-sbc/Power-Control-Panel-v2#35]
V0.1.13
OneXPlayer Mini Gundam

Hotkeys for QAM and OSK don't work. Hold keys for over 1 second does nothing.

**Comment by sanpats** [comment]
Intel 1260P

**Comment by sanpats** [comment]
Tested with 0.1.12 and it works perfectly.

**Comment by project-sbc** [comment]
Yup I know why, should be fixed in 0.2.1
