### ISSUE TITLE
Windows Start Up Not Working

### ISSUE THREAD

**Issue by Nagakuro** [project-sbc/Power-Control-Panel-v2#53]
So I finally got the app working and it's working great, but I can't get it to run at start up for the life of me, even with the "Start with Windows" Setting enabled, I tried task scheduler, I tried adding it through the startup folder with a shortcut, I tried registry editing, I've added an exception through firewall, I turned UAC off so the admin request doesn't pop up. 

I'm completely and utterly stumped, this software is great and allows me to set all my games to run at different TDPs on my onexplayer on battery and when docked/charging, This software is so much better than the current OXP Software, so I really want it to figure out how to get it to boot at start up.

**Comment by project-sbc** [comment]
Hey are you on discord? Would like to diagnose further. Btw got a major release coming that will launch this even further

Discord ProjectSBC#9711

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Nagakuro ***@***.***>
Sent: Friday, November 25, 2022 3:05:58 PM
To: project-sbc/Power-Control-Panel-v2 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [project-sbc/Power-Control-Panel-v2] Windows Start Up Not Working (Issue #53)


So I finally got the app working and it's working great, but I can't get it to run at start up for the life of me, even with the "Start with Windows" Setting enabled, I tried task scheduler, I tried adding it through the startup folder with a shortcut, I tried registry editing, I've added an exception through firewall, I turned UAC off so the admin request doesn't pop up.

I'm completely and utterly stumped, this software is great and allows me to set all my games to run at different TDPs on my onexplayer on battery and when docked/charging, This software is so much better than the current OXP Software, so I really want it to figure out how to get it to boot at start up.

**Comment by Nagakuro** [comment]
Sending a friend request on discord I'm Kentun

**Comment by project-sbc** [comment]
User needed to move install from C:\ to some other directory

**Comment by Syizuril** [comment]
hello, I also experienced the same thing, I saved it outside the C:\ disk but the start up still doesn't work
