### ISSUE TITLE
Sidebar Cropping

### ISSUE THREAD

**Issue by victoriemini** [project-sbc/Power-Control-Panel-v2#7]
Hey! I'm trying it out on a Anbernic Win600 with Windows 11. When i click L1 + R1 + Right it opens the sidebar, but for some reason it's cropped. I'm at 100% scaling. Any ideas
![6FA01058-1D9C-419C-B7DC-D2173E729B96](https://user-images.githubusercontent.com/70662873/182684293-c75dc948-6c89-48e9-be67-6397d253766c.jpg)
?

**Comment by cheungyau2022** [comment]
I have the exact same issue. Can't change TDP because of this. I have to open the main window to see the numbers.

**Comment by project-sbc** [comment]
Can you take a picture of the whole screen?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by victoriemini** [comment]
![IMG_4671](https://user-images.githubusercontent.com/70662873/183104896-4ec2a4f0-e06b-4656-a1ec-151f3a1f67fd.JPG)

**Comment by project-sbc** [comment]
I’ll have a fix either tonight or tomorrow

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by project-sbc** [comment]
The side menu is fixed width now and this shouldn’t be an issue anymore
