### ISSUE TITLE
Power Control Panel does not work on Windows with Russian language

### ISSUE THREAD

**Issue by Eric-Newman** [project-sbc/Power-Control-Panel-v2#8]
Good afternoon. I installed Power Control Panel v2, but when I run the program and change the TDP, this is the error. What could be the reason?

Error: ChangeTDP.cs Run AMD TDP Read: Input string was not in a correct format, processRyzenAdj is
https://fastpic.org/view/120/2022/0807/3f6a229a933b31c6968e9366c1b3d8d1.png

Windows 10 Pro, Anbernic Win600,
Installed windowsdesktop-runtime-6.0.3-win-x64.exe, Visual С++ 2005-2022

**Comment by Eric-Newman** [comment]
good afternoon. I found the problem myself and asked you to make changes.

If Windows is set to English, then the program works without errors.

If you change the language to Russian, then the error indicated above occurs.

**Comment by Eric-Newman** [comment]
I can record a video with an error and send it to you

**Comment by MrPropre** [comment]
Same for French language. I dont think it works for any other language than English

**Comment by project-sbc** [comment]
It has to do with the use of a comma, I just added a fix that will come in  the next release

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Eric-Newman** [comment]
Good afternoon. In an hour I will write to you about the results of testing.

**Comment by Eric-Newman** [comment]
> Just released patch, can you two try and let me know


does not work!

**Comment by project-sbc** [comment]
Are you on discord? Would like to try to diagnose this further ProjecrSBC#9711

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Eric-Newman** [comment]
I wrote in discord

**Comment by project-sbc** [comment]
Fixed per discord conversation

**Comment by project-sbc** [comment]
Fixed in latest release
