### ISSUE TITLE
Change Quick Access Menu Shortcut

### ISSUE THREAD

**Issue by bigwhitebuddha** [project-sbc/Power-Control-Panel-v2#9]
This app has been amazing so far. My only issue I have encountered is being unable to remap the shortcut for opening the quick access menu. 

Currently, it is mapped to LB+RB+Right-DPAD. I think being able to remap this would be helpful

**Comment by andyktaylor** [comment]
Yes please! If you could open this option to allow is to map to any button or key combination, that would be amazing

**Comment by project-sbc** [comment]
on the to do list

**Comment by project-sbc** [comment]
Implemented as of version 0.1.13
